version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: user_details
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springboot-app:
    build: .
    container_name: berrypopservice-service
    depends_on:
      - postgres
    environment:
      RDS_HOSTNAME: postgres
      RDS_PORT: 5432
      RDS_DB_NAME: user_details
      RDS_USERNAME: postgres
      RDS_PASSWORD: 123
    ports:
      - "5001:5001"
    restart: always

volumes:
  pgdata:
